### ISSUE TITLE
Crypto memes thread

### ISSUE THREAD

**Issue by zipplet** [responsible-financial-innovation-act22/RFIA-bill#47]
![theplanbitcoin](https://user-images.githubusercontent.com/316735/175437983-f8b21a98-7a79-42a3-91fe-2c171f6c2cba.png)

**Comment by joelsgp** [comment]
Of course you guys would be so smug and entitled and celebrating that crypto is finally dead for the 1473838th time.

But not me. I'm in it for the long game. I hedge my bets. Bitcoin going down 70%? Not good enough for me. I wait until it's all collapsed. Zero. Literally zero.

Because then I can buy all of it. Any number times zero is still zero. It's mathematically proven. You can't get better than this. The whole pool of coins, waiting for me to be transferred in my web of wallets, testing the limits of the Gini coefficient.

And then, anyone who wants Bitcoin will have to buy it from me. But they will have to pay dearly for it. Not giving it away for cents on the coin like in the early days. I know what I have and what's it worth. I waited so long for this.

You can have a small share of the tremendous wealth I own then. Heck, you'll be glad for every Satoshi. And you'll regret throwing the towel when "it all went to zero". Because this is the best thing that can happen to you and to Bitcoin, but you just can't see it.
